name: Deploy to GitHub Pages

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x.x

      # Runs a set of commands using the runners shell
      - name: Install WASM tools
        run: dotnet workload install wasm-tools
      - name: Publish .NET Project
        run: dotnet publish BlazorExperiments/BlazorExperiments.UI.csproj -c Release -o release --nologo
      - name: Publish .NET Project with AOT
        run: dotnet publish BlazorExperiments/BlazorExperiments.UI.csproj -c Release -p:RunAOTCompilation=true -p:WasmStripILAfterAOT=true -o release-aot --nologo
      - name: check current directory
        run: ls -la release-aot/wwwroot && pwd 
      - name: Fix base path for Blazor AOT app
        run: sed -i 's/<base href="\/blazor\/" \/>/<base href="\/blazor-aot\/" \/>/g' release-aot/wwwroot/index.html
      - name: check index.html
        run: cat release-aot/wwwroot/index.html

      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.6.9
        with:
          branch: main
          folder: release/wwwroot
          repository-name: iSeiryu/iseiryu.github.io
          target-folder: blazor
          token: ${{ secrets.DEPLOY_TOKEN }}
      
      - name: Commit wwwroot AOT to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.6.9
        with:
          branch: main
          folder: release-aot/wwwroot
          repository-name: iSeiryu/iseiryu.github.io
          target-folder: blazor-aot
          token: ${{ secrets.DEPLOY_TOKEN }}
